package swagger

import (
    _ "lab2/internal/swagger/docs" // docs is generated by swag
)

// Init инициализирует Swagger (вызывается в main)
func Init() {
    // Аннотации уже обработаны командой `swag init`
    // Этот файл нужен для импорта docs и инициализации
}